name: main

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: checkout submodules
        run: "git submodule update --init"
      - name: Docker Login
        env:
          DOCKER_REGISTRY: ghcr.io
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: docker login $DOCKER_REGISTRY --username "$DOCKER_USER" --password "$DOCKER_PASS"
      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.7.0/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Earthly version
        run: earthly --version
      - name: version
        id: version
        run: echo "sha_short=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_OUTPUT
      - name: check version
        env:
          VERSION: ${{ steps.version.outputs.sha_short }}
        run: echo $VERSION
      - name: Run build
        env:
          EARTHLY_BUILD_ARGS: "VERSION"
          VERSION: ${{ steps.version.outputs.sha_short }}
          GH_USER: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EARTHLY_SECRETS: "GH_USER,GH_TOKEN"
        run: |
          earthly -P --ci --output --push +all
